import type { DealType, OfferSource } from "../domain/types";

/**
 * Development sample data.
 *
 * Everything here is DEMO/SAMPLE content used to exercise the UI. Deals are
 * stored with `is_demo = 1`, the site labels them as sample data, and coupon
 * codes are deliberately prefixed `DEMO-` so they cannot be mistaken for real
 * offers. Destination links point at store home pages only.
 *
 * The Amazon entries carry `legacy:` external ids because they were the original
 * project's sample product catalogue; the legacy `/product/[id]` URLs still
 * resolve through them.
 */

export interface DemoMerchant {
  name: string;
  slug: string;
  websiteUrl: string;
  category: string;
  description: string;
  network: OfferSource;
  featured?: boolean;
  qualityScore?: number;
  affiliateBaseUrl?: string;
}

export interface DemoDeal {
  merchantSlug: string;
  title: string;
  type: DealType;
  couponCode?: string;
  description: string;
  destinationUrl: string;
  originalPrice?: number;
  salePrice?: number;
  discountPercent?: number;
  discountAmount?: number;
  category?: string;
  terms?: string;
  /** Relative dates keep the sample data looking current whenever it is seeded. */
  createdDaysAgo?: number;
  startsInDays?: number;
  expiresInDays?: number;
  verified?: boolean;
  verifiedDaysAgo?: number;
  status?: "ACTIVE" | "EXPIRED" | "PENDING" | "DISABLED";
  featured?: boolean;
  trending?: boolean;
  clickCount?: number;
  workedYes?: number;
  workedNo?: number;
  source: OfferSource;
  externalId?: string;
}

export const DEMO_MERCHANTS: DemoMerchant[] = [
  {
    name: "Amazon",
    slug: "amazon",
    websiteUrl: "https://www.amazon.com/",
    category: "Electronics",
    description:
      "General marketplace covering electronics, home, beauty, toys and books. Treated as one merchant among many in DealScout.",
    network: "AMAZON",
    featured: true,
    qualityScore: 78,
  },
  {
    name: "Samsung",
    slug: "samsung",
    websiteUrl: "https://www.samsung.com/us/",
    category: "Electronics",
    description: "Phones, tablets, TVs and home appliances direct from the manufacturer.",
    network: "IMPACT",
    featured: true,
    qualityScore: 80,
  },
  {
    name: "Nike",
    slug: "nike",
    websiteUrl: "https://www.nike.com/",
    category: "Fashion",
    description: "Footwear, apparel and training gear, including a regularly refreshed sale section.",
    network: "PARTNERIZE",
    featured: true,
    qualityScore: 82,
  },
  {
    name: "Best Buy",
    slug: "best-buy",
    websiteUrl: "https://www.bestbuy.com/",
    category: "Electronics",
    description: "Consumer electronics retailer with frequent open-box and weekly deal events.",
    network: "CJ",
    qualityScore: 74,
  },
  {
    name: "Wayfair",
    slug: "wayfair",
    websiteUrl: "https://www.wayfair.com/",
    category: "Home & Kitchen",
    description: "Furniture and home goods with rotating category-wide sale events.",
    network: "CJ",
    qualityScore: 68,
  },
  {
    name: "Sephora",
    slug: "sephora",
    websiteUrl: "https://www.sephora.com/",
    category: "Beauty",
    description: "Beauty and skincare retailer known for gift-with-purchase promotions.",
    network: "RAKUTEN",
    featured: true,
    qualityScore: 76,
  },
  {
    name: "REI",
    slug: "rei",
    websiteUrl: "https://www.rei.com/",
    category: "Sports & Outdoors",
    description: "Outdoor gear co-op with member events and seasonal clearance.",
    network: "DIRECT",
    qualityScore: 72,
  },
  {
    name: "Chewy",
    slug: "chewy",
    websiteUrl: "https://www.chewy.com/",
    category: "Pets",
    description: "Pet food, supplies and pharmacy with autoship discounts.",
    network: "IMPACT",
    qualityScore: 70,
  },
  {
    name: "Expedia",
    slug: "expedia",
    websiteUrl: "https://www.expedia.com/",
    category: "Travel",
    description: "Flights, hotels and package bookings with member-only pricing.",
    network: "PARTNERIZE",
    qualityScore: 64,
  },
  {
    name: "LEGO",
    slug: "lego",
    websiteUrl: "https://www.lego.com/",
    category: "Toys & Games",
    description: "Building sets, with frequent gift-with-purchase offers on the official store.",
    network: "AWIN",
    qualityScore: 79,
  },
  {
    name: "Adobe",
    slug: "adobe",
    websiteUrl: "https://www.adobe.com/",
    category: "Software & Services",
    description: "Creative and document software sold on subscription.",
    network: "IMPACT",
    qualityScore: 66,
  },
  {
    name: "Zappos",
    slug: "zappos",
    websiteUrl: "https://www.zappos.com/",
    category: "Fashion",
    description: "Shoes and apparel with free shipping and returns.",
    network: "DIRECT",
    qualityScore: 71,
  },
  {
    name: "Target",
    slug: "target",
    websiteUrl: "https://www.target.com/",
    category: "Home & Kitchen",
    description: "General merchandise retailer with weekly circle offers.",
    network: "IMPACT",
    qualityScore: 73,
  },
  {
    name: "HelloFresh",
    slug: "hellofresh",
    websiteUrl: "https://www.hellofresh.com/",
    category: "Food & Drink",
    description: "Meal-kit subscription with introductory box discounts.",
    network: "AWIN",
    qualityScore: 60,
  },
];

/** Amazon entries ported from the original sample product catalogue. */
const AMAZON_LEGACY_DEALS: DemoDeal[] = [
  {
    merchantSlug: "amazon",
    title: "AuroraSound Wireless Noise-Cancelling Headphones",
    type: "DEAL",
    description:
      "40-hour battery, adaptive noise cancellation and memory-foam ear cups. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 249.99,
    salePrice: 129.99,
    category: "Electronics",
    createdDaysAgo: 2,
    expiresInDays: 9,
    verified: true,
    verifiedDaysAgo: 1,
    featured: true,
    trending: true,
    clickCount: 184,
    workedYes: 22,
    workedNo: 3,
    source: "AMAZON",
    externalId: "legacy:wireless-anc-headphones",
  },
  {
    merchantSlug: "amazon",
    title: "BeamCast 4K Streaming Stick with Voice Remote",
    type: "DEAL",
    description: "4K HDR streaming stick with a voice remote. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 49.99,
    salePrice: 27.99,
    category: "Electronics",
    createdDaysAgo: 4,
    expiresInDays: 14,
    verified: true,
    verifiedDaysAgo: 3,
    clickCount: 96,
    workedYes: 11,
    workedNo: 1,
    source: "AMAZON",
    externalId: "legacy:smart-4k-streaming-stick",
  },
  {
    merchantSlug: "amazon",
    title: "CremaPro 15-Bar Espresso & Cappuccino Machine",
    type: "DEAL",
    description:
      "15-bar pump espresso machine with a steam wand for lattes, cappuccinos and other coffee drinks. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 299,
    salePrice: 179,
    category: "Home & Kitchen",
    createdDaysAgo: 6,
    expiresInDays: 21,
    verified: true,
    verifiedDaysAgo: 5,
    clickCount: 64,
    workedYes: 7,
    source: "AMAZON",
    externalId: "legacy:espresso-machine",
  },
  {
    merchantSlug: "amazon",
    title: "CrispWave 6-Quart Digital Air Fryer",
    type: "DEAL",
    description: "Six-quart air fryer with eight one-touch presets. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 119.99,
    salePrice: 59.99,
    category: "Home & Kitchen",
    createdDaysAgo: 1,
    expiresInDays: 6,
    verified: true,
    verifiedDaysAgo: 1,
    featured: true,
    clickCount: 142,
    workedYes: 18,
    workedNo: 2,
    source: "AMAZON",
    externalId: "legacy:air-fryer-6qt",
  },
  {
    merchantSlug: "amazon",
    title: "GlowLab Vitamin C Brightening Serum",
    type: "DEAL",
    description: "Vitamin C serum with hyaluronic acid. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 29.95,
    salePrice: 14.95,
    category: "Beauty",
    createdDaysAgo: 9,
    expiresInDays: 30,
    clickCount: 41,
    source: "AMAZON",
    externalId: "legacy:vitamin-c-serum",
  },
  {
    merchantSlug: "amazon",
    title: "PearlSonic Rechargeable Electric Toothbrush",
    type: "DEAL",
    description: "Sonic toothbrush with five modes and a 30-day battery. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 69.99,
    salePrice: 34.99,
    category: "Beauty",
    createdDaysAgo: 12,
    expiresInDays: 18,
    verified: true,
    verifiedDaysAgo: 11,
    clickCount: 33,
    workedYes: 4,
    workedNo: 1,
    source: "AMAZON",
    externalId: "legacy:electric-toothbrush",
  },
  {
    merchantSlug: "amazon",
    title: "BrickMasters 1,000-Piece Creative Building Set",
    type: "DEAL",
    description: "A 1,000-piece building set in twelve colours. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 79.99,
    salePrice: 39.99,
    category: "Toys & Games",
    createdDaysAgo: 3,
    expiresInDays: 11,
    clickCount: 58,
    workedYes: 6,
    source: "AMAZON",
    externalId: "legacy:building-blocks-set",
  },
  {
    merchantSlug: "amazon",
    title: "Quest Legends Cooperative Board Game",
    type: "DEAL",
    description: "Cooperative board game for two to five players. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 44.99,
    salePrice: 24.49,
    category: "Toys & Games",
    createdDaysAgo: 16,
    clickCount: 12,
    source: "AMAZON",
    externalId: "legacy:board-game-night",
  },
  {
    merchantSlug: "amazon",
    title: "TrailGlide Lightweight Running Shoes",
    type: "DEAL",
    description: "Lightweight running shoes for road and trail. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 99.99,
    salePrice: 54.99,
    category: "Sports & Outdoors",
    createdDaysAgo: 5,
    expiresInDays: 8,
    verified: true,
    verifiedDaysAgo: 4,
    clickCount: 77,
    workedYes: 9,
    workedNo: 2,
    source: "AMAZON",
    externalId: "legacy:running-shoes",
  },
  {
    merchantSlug: "amazon",
    title: "SummitFlask 32oz Insulated Water Bottle",
    type: "DEAL",
    description: "Vacuum-insulated 32oz bottle with a flip-straw lid. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 34.99,
    salePrice: 19.99,
    category: "Sports & Outdoors",
    createdDaysAgo: 8,
    expiresInDays: 25,
    clickCount: 27,
    source: "AMAZON",
    externalId: "legacy:insulated-water-bottle",
  },
  {
    merchantSlug: "amazon",
    title: "Deep Focus: The Science of Getting Things Done",
    type: "DEAL",
    description: "Productivity title covering twelve focus frameworks. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 24,
    salePrice: 12.99,
    category: "Books & Media",
    createdDaysAgo: 21,
    clickCount: 9,
    source: "AMAZON",
    externalId: "legacy:productivity-book",
  },
  {
    merchantSlug: "amazon",
    title: "30-Minute Weeknight Dinners Cookbook",
    type: "DEAL",
    description: "125 recipes, each under thirty minutes. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 21.99,
    salePrice: 9.99,
    category: "Books & Media",
    createdDaysAgo: 26,
    clickCount: 6,
    source: "AMAZON",
    externalId: "legacy:cookbook-weeknight",
  },
  {
    merchantSlug: "amazon",
    title: "TypeForge Hot-Swappable Mechanical Keyboard",
    type: "DEAL",
    description: "Hot-swappable mechanical keyboard with per-key lighting. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 129.99,
    salePrice: 69.99,
    category: "Electronics",
    createdDaysAgo: 7,
    expiresInDays: 4,
    verified: true,
    verifiedDaysAgo: 2,
    trending: true,
    clickCount: 118,
    workedYes: 14,
    workedNo: 1,
    source: "AMAZON",
    externalId: "legacy:mechanical-keyboard",
  },
  {
    merchantSlug: "amazon",
    title: "TidyBot Self-Emptying Robot Vacuum",
    type: "DEAL",
    description: "Robot vacuum with LiDAR mapping and a self-emptying base. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 399,
    salePrice: 219,
    category: "Home & Kitchen",
    createdDaysAgo: 2,
    expiresInDays: 12,
    verified: true,
    verifiedDaysAgo: 1,
    featured: true,
    clickCount: 203,
    workedYes: 25,
    workedNo: 4,
    source: "AMAZON",
    externalId: "legacy:robot-vacuum",
  },
  {
    merchantSlug: "amazon",
    title: "ZenGrip Extra-Thick Non-Slip Yoga Mat",
    type: "DEAL",
    description: "8mm yoga mat with a carry strap. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 42.99,
    salePrice: 22.99,
    category: "Sports & Outdoors",
    createdDaysAgo: 14,
    expiresInDays: 20,
    clickCount: 21,
    source: "AMAZON",
    externalId: "legacy:yoga-mat",
  },
  {
    merchantSlug: "amazon",
    title: "LumaGlow LED Light Therapy Face Mask",
    type: "DEAL",
    description: "Cordless LED therapy mask with seven modes. Sample record used for interface testing.",
    destinationUrl: "https://www.amazon.com/",
    originalPrice: 109.99,
    salePrice: 49.99,
    category: "Beauty",
    createdDaysAgo: 30,
    expiresInDays: -2,
    status: "EXPIRED",
    clickCount: 44,
    workedYes: 2,
    workedNo: 5,
    source: "AMAZON",
    externalId: "legacy:led-face-mask",
  },
];

const OTHER_MERCHANT_DEALS: DemoDeal[] = [
  {
    merchantSlug: "samsung",
    title: "Extra 10% off Galaxy accessories with code",
    type: "PROMO_CODE",
    couponCode: "DEMO-GALAXY10",
    description:
      "Sample promo-code record: an extra percentage off accessories at checkout. Used to test the code-reveal flow.",
    destinationUrl: "https://www.samsung.com/us/",
    discountPercent: 10,
    category: "Electronics",
    terms: "Sample terms. Real merchant offers usually exclude bundles and clearance items.",
    createdDaysAgo: 1,
    expiresInDays: 5,
    verified: true,
    verifiedDaysAgo: 1,
    featured: true,
    trending: true,
    clickCount: 231,
    workedYes: 34,
    workedNo: 5,
    source: "IMPACT",
    externalId: "demo-impact-1001",
  },
  {
    merchantSlug: "samsung",
    title: "Up to 35% off selected 4K and QLED televisions",
    type: "DEAL",
    description: "Sample deal record covering a television category promotion.",
    destinationUrl: "https://www.samsung.com/us/",
    discountPercent: 35,
    category: "Electronics",
    createdDaysAgo: 5,
    expiresInDays: 16,
    verified: true,
    verifiedDaysAgo: 2,
    clickCount: 87,
    workedYes: 8,
    source: "IMPACT",
    externalId: "demo-impact-1002",
  },
  {
    merchantSlug: "nike",
    title: "20% off full-price styles for members",
    type: "PROMO_CODE",
    couponCode: "DEMO-MEMBER20",
    description: "Sample member promo-code record used to test the promo-code experience.",
    destinationUrl: "https://www.nike.com/",
    discountPercent: 20,
    category: "Fashion",
    terms: "Sample terms. Membership and category exclusions typically apply on real offers.",
    createdDaysAgo: 2,
    expiresInDays: 3,
    verified: true,
    verifiedDaysAgo: 1,
    featured: true,
    trending: true,
    clickCount: 412,
    workedYes: 61,
    workedNo: 7,
    source: "PARTNERIZE",
    externalId: "demo-partnerize-2001",
  },
  {
    merchantSlug: "nike",
    title: "Up to 50% off the sale section",
    type: "DEAL",
    description: "Sample clearance record with no code required.",
    destinationUrl: "https://www.nike.com/",
    discountPercent: 50,
    category: "Fashion",
    createdDaysAgo: 4,
    expiresInDays: 12,
    verified: true,
    verifiedDaysAgo: 3,
    clickCount: 156,
    workedYes: 19,
    workedNo: 2,
    source: "PARTNERIZE",
    externalId: "demo-partnerize-2002",
  },
  {
    merchantSlug: "nike",
    title: "Free shipping on orders over $50",
    type: "PROMO_CODE",
    couponCode: "DEMO-SHIPFREE",
    description: "Sample shipping-offer record. Shipping offers store no percentage discount.",
    destinationUrl: "https://www.nike.com/",
    category: "Fashion",
    createdDaysAgo: 11,
    expiresInDays: 40,
    clickCount: 63,
    workedYes: 9,
    workedNo: 3,
    source: "MANUAL",
  },
  {
    merchantSlug: "best-buy",
    title: "$150 off selected gaming laptops",
    type: "DEAL",
    description: "Sample fixed-amount discount record used to test amount-based savings display.",
    destinationUrl: "https://www.bestbuy.com/",
    discountAmount: 150,
    category: "Electronics",
    createdDaysAgo: 3,
    expiresInDays: 2,
    verified: true,
    verifiedDaysAgo: 1,
    clickCount: 128,
    workedYes: 13,
    workedNo: 2,
    source: "CJ",
    externalId: "demo-cj-3001",
  },
  {
    merchantSlug: "best-buy",
    title: "Open-box electronics from 30% off",
    type: "DEAL",
    description: "Sample open-box clearance record.",
    destinationUrl: "https://www.bestbuy.com/",
    discountPercent: 30,
    category: "Electronics",
    createdDaysAgo: 9,
    expiresInDays: 22,
    clickCount: 39,
    source: "CJ",
    externalId: "demo-cj-3002",
  },
  {
    merchantSlug: "wayfair",
    title: "Up to 60% off area rugs",
    type: "DEAL",
    description: "Sample category sale record with a high stored discount.",
    destinationUrl: "https://www.wayfair.com/",
    discountPercent: 60,
    category: "Home & Kitchen",
    createdDaysAgo: 1,
    expiresInDays: 4,
    verified: true,
    verifiedDaysAgo: 1,
    featured: true,
    clickCount: 173,
    workedYes: 21,
    workedNo: 3,
    source: "CJ",
    externalId: "demo-cj-3003",
  },
  {
    merchantSlug: "wayfair",
    title: "$25 off your first order of $200 or more",
    type: "PROMO_CODE",
    couponCode: "DEMO-FIRST25",
    description: "Sample first-order promo code with a minimum spend.",
    destinationUrl: "https://www.wayfair.com/",
    discountAmount: 25,
    category: "Home & Kitchen",
    terms: "Sample terms. New customers only on comparable real-world offers.",
    createdDaysAgo: 7,
    expiresInDays: 30,
    clickCount: 52,
    workedYes: 5,
    workedNo: 4,
    source: "MANUAL",
  },
  {
    merchantSlug: "sephora",
    title: "15% off skincare with code",
    type: "PROMO_CODE",
    couponCode: "DEMO-GLOW15",
    description: "Sample beauty promo-code record.",
    destinationUrl: "https://www.sephora.com/",
    discountPercent: 15,
    category: "Beauty",
    createdDaysAgo: 2,
    expiresInDays: 6,
    verified: true,
    verifiedDaysAgo: 2,
    trending: true,
    clickCount: 267,
    workedYes: 38,
    workedNo: 6,
    source: "RAKUTEN",
    externalId: "demo-rakuten-4001",
  },
  {
    merchantSlug: "sephora",
    title: "Free 4-piece sample set with any $75 purchase",
    type: "DEAL",
    description: "Sample gift-with-purchase record. No percentage discount is stored for this type of offer.",
    destinationUrl: "https://www.sephora.com/",
    category: "Beauty",
    createdDaysAgo: 6,
    expiresInDays: 10,
    clickCount: 74,
    workedYes: 11,
    source: "RAKUTEN",
    externalId: "demo-rakuten-4002",
  },
  {
    merchantSlug: "rei",
    title: "Up to 40% off camping and hiking gear",
    type: "DEAL",
    description: "Sample seasonal outdoor clearance record.",
    destinationUrl: "https://www.rei.com/",
    discountPercent: 40,
    category: "Sports & Outdoors",
    createdDaysAgo: 4,
    expiresInDays: 8,
    verified: true,
    verifiedDaysAgo: 3,
    clickCount: 91,
    workedYes: 12,
    workedNo: 1,
    source: "CSV",
    externalId: "demo-csv-5001",
  },
  {
    merchantSlug: "chewy",
    title: "35% off your first Autoship order",
    type: "PROMO_CODE",
    couponCode: "DEMO-AUTO35",
    description: "Sample subscription promo-code record.",
    destinationUrl: "https://www.chewy.com/",
    discountPercent: 35,
    category: "Pets",
    terms: "Sample terms. Subscription offers are usually limited to first orders.",
    createdDaysAgo: 3,
    expiresInDays: 45,
    verified: true,
    verifiedDaysAgo: 3,
    clickCount: 143,
    workedYes: 24,
    workedNo: 3,
    source: "IMPACT",
    externalId: "demo-impact-1003",
  },
  {
    merchantSlug: "chewy",
    title: "Buy 3 get 1 free on selected dog treats",
    type: "DEAL",
    description: "Sample multi-buy record. Multi-buy offers store no single percentage value.",
    destinationUrl: "https://www.chewy.com/",
    category: "Pets",
    createdDaysAgo: 13,
    expiresInDays: 14,
    clickCount: 22,
    source: "CSV",
    externalId: "demo-csv-5002",
  },
  {
    merchantSlug: "expedia",
    title: "10% off selected hotel bookings with code",
    type: "PROMO_CODE",
    couponCode: "DEMO-STAY10",
    description: "Sample travel promo-code record.",
    destinationUrl: "https://www.expedia.com/",
    discountPercent: 10,
    category: "Travel",
    terms: "Sample terms. Real travel offers carry booking and travel-date windows.",
    createdDaysAgo: 5,
    expiresInDays: 20,
    verified: true,
    verifiedDaysAgo: 5,
    clickCount: 68,
    workedYes: 7,
    workedNo: 5,
    source: "PARTNERIZE",
    externalId: "demo-partnerize-2003",
  },
  {
    merchantSlug: "lego",
    title: "Double VIP points on all orders",
    type: "DEAL",
    description: "Sample loyalty-points record with no monetary discount stored.",
    destinationUrl: "https://www.lego.com/",
    category: "Toys & Games",
    createdDaysAgo: 2,
    expiresInDays: 7,
    verified: true,
    verifiedDaysAgo: 1,
    clickCount: 112,
    workedYes: 16,
    workedNo: 1,
    source: "AWIN",
    externalId: "demo-awin-6001",
  },
  {
    merchantSlug: "lego",
    title: "Up to 30% off retiring sets",
    type: "DEAL",
    description: "Sample clearance record for retiring product lines.",
    destinationUrl: "https://www.lego.com/",
    discountPercent: 30,
    category: "Toys & Games",
    createdDaysAgo: 8,
    expiresInDays: 18,
    clickCount: 47,
    workedYes: 4,
    source: "AWIN",
    externalId: "demo-awin-6002",
  },
  {
    merchantSlug: "adobe",
    title: "40% off the first year of an annual plan",
    type: "PROMO_CODE",
    couponCode: "DEMO-CREATE40",
    description: "Sample software subscription promo-code record.",
    destinationUrl: "https://www.adobe.com/",
    discountPercent: 40,
    category: "Software & Services",
    createdDaysAgo: 1,
    expiresInDays: 2,
    verified: true,
    verifiedDaysAgo: 1,
    featured: true,
    trending: true,
    clickCount: 318,
    workedYes: 44,
    workedNo: 9,
    source: "IMPACT",
    externalId: "demo-impact-1004",
  },
  {
    merchantSlug: "zappos",
    title: "Extra 15% off clearance footwear",
    type: "PROMO_CODE",
    couponCode: "DEMO-STEP15",
    description: "Sample stacked-clearance promo-code record.",
    destinationUrl: "https://www.zappos.com/",
    discountPercent: 15,
    category: "Fashion",
    createdDaysAgo: 6,
    expiresInDays: 9,
    clickCount: 58,
    workedYes: 6,
    workedNo: 2,
    source: "DIRECT",
    externalId: "demo-direct-7001",
  },
  {
    merchantSlug: "target",
    title: "Spend $50, get a $10 gift card on household essentials",
    type: "DEAL",
    description: "Sample threshold-reward record.",
    destinationUrl: "https://www.target.com/",
    discountAmount: 10,
    category: "Home & Kitchen",
    createdDaysAgo: 3,
    expiresInDays: 5,
    verified: true,
    verifiedDaysAgo: 2,
    clickCount: 96,
    workedYes: 14,
    workedNo: 2,
    source: "IMPACT",
    externalId: "demo-impact-1005",
  },
  {
    merchantSlug: "hellofresh",
    title: "$90 off across your first four boxes",
    type: "PROMO_CODE",
    couponCode: "DEMO-FRESH90",
    description: "Sample meal-kit introductory promo-code record.",
    destinationUrl: "https://www.hellofresh.com/",
    discountAmount: 90,
    category: "Food & Drink",
    terms: "Sample terms. Introductory offers are normally limited to new subscribers.",
    createdDaysAgo: 4,
    expiresInDays: 28,
    verified: true,
    verifiedDaysAgo: 4,
    clickCount: 187,
    workedYes: 26,
    workedNo: 11,
    source: "AWIN",
    externalId: "demo-awin-6003",
  },
  {
    merchantSlug: "hellofresh",
    title: "Free dessert in every box for two months",
    type: "DEAL",
    description: "Sample add-on record with no discount value stored.",
    destinationUrl: "https://www.hellofresh.com/",
    category: "Food & Drink",
    createdDaysAgo: 20,
    expiresInDays: -3,
    status: "EXPIRED",
    clickCount: 31,
    workedYes: 3,
    workedNo: 2,
    source: "AWIN",
    externalId: "demo-awin-6004",
  },
  {
    merchantSlug: "expedia",
    title: "Sample offer awaiting review",
    type: "PROMO_CODE",
    couponCode: "DEMO-PENDING",
    description:
      "Sample PENDING record. Pending offers are hidden from the public site until an administrator approves them.",
    destinationUrl: "https://www.expedia.com/",
    discountPercent: 12,
    category: "Travel",
    createdDaysAgo: 1,
    expiresInDays: 30,
    status: "PENDING",
    source: "USER_SUBMISSION",
  },
  {
    merchantSlug: "best-buy",
    title: "Sample disabled offer",
    type: "DEAL",
    description:
      "Sample DISABLED record, kept to show that disabled offers stay in the database without being published.",
    destinationUrl: "https://www.bestbuy.com/",
    discountPercent: 25,
    category: "Electronics",
    createdDaysAgo: 15,
    status: "DISABLED",
    source: "CSV",
    externalId: "demo-csv-5003",
  },
  {
    merchantSlug: "target",
    title: "Sample expired weekly promotion",
    type: "PROMO_CODE",
    couponCode: "DEMO-LASTWEEK",
    description: "Sample EXPIRED record, retained for analytics and history.",
    destinationUrl: "https://www.target.com/",
    discountPercent: 20,
    category: "Home & Kitchen",
    createdDaysAgo: 24,
    expiresInDays: -6,
    status: "EXPIRED",
    clickCount: 54,
    workedYes: 6,
    workedNo: 4,
    source: "IMPACT",
    externalId: "demo-impact-1006",
  },
];

export const DEMO_DEALS: DemoDeal[] = [...AMAZON_LEGACY_DEALS, ...OTHER_MERCHANT_DEALS];

/** Recorded clicks per channel, so the analytics screens have data to compare. */
export const DEMO_CLICK_CHANNELS: { src: string | null; weight: number }[] = [
  { src: "youtube", weight: 34 },
  { src: "tiktok", weight: 26 },
  { src: "facebook", weight: 14 },
  { src: null, weight: 20 },
  { src: "instagram", weight: 6 },
];
